### ISSUE TITLE
How to modify maximum speed and acceleration

### ISSUE THREAD

**Issue by cheslee-z** [Zhefan-Xu/CERLAB-UAV-Autonomy#10]
Hi,

For real flight, I set `desired_velocity `to 5, `desired_acceleration` to 1.5, But the actual velocity is probably less than 1m/s. 

I feel it makes sense to modify this parameter in the simulation. Can you give me some advice?

Thank you.

**Comment by Zhefan-Xu** [comment]
Hi @cheslee-z , so for velocity I would recommend trying the following combination:
v = 0.5-1.0 m/s, a = 1-2m/s^2
v = 1.0-2.0 m/s, a = 2-4m/s^2
v = 2.0-3 m/s, a = 4-6m/s^2
If you set a high velocity, you will have to also increase the acceleration limit. Also, I highly don't recommend to set a velocity beyond 3m/s and usually 1-2m/s will be fine for tasks indoor.

**Comment by cheslee-z** [comment]
Hi @Zhefan-Xu, thank You for Your Helpful Suggestions!
