### ISSUE TITLE
Map update is too slow during real flight

### ISSUE THREAD

**Issue by cheslee-z** [Zhefan-Xu/CERLAB-UAV-Autonomy#11]
Hi, @Zhefan-Xu, thanks for your outstanding work.

I encountered another problem during real flight: it seems that the voxel update of dynamic obstacles is too slow, causing the UAV to easily pause in front of dynamic obstacles. And the trajectory seems to have not been re-planned. Could you give me some advice?
<img width="425" alt="Snipaste_2024-03-29_18-56-45" src="https://github.com/Zhefan-Xu/CERLAB-UAV-Autonomy/assets/46998045/195b776c-7a67-4a8d-a534-f686c81a2785">

**Comment by Zhefan-Xu** [comment]
Hi @cheslee-z, this should not happen if the dynamic obstacle is detected. Could you provide more information?

**Comment by cheslee-z** [comment]
> Hi @cheslee-z, this should not happen if the dynamic obstacle is detected. Could you provide more information?

Hi, thank you for your reply. I found that there seems to be a discrepancy between the real experiment and the simulation experiment codes. I'm not sure what I have modified, but this issue has now been resolved.

**Comment by Zhefan-Xu** [comment]
@cheslee-z I think I know the reason. You have to change the fake detector param to False
