### ISSUE TITLE
Run Autonomy DEMO  报错，Autonomous Navigation bug

### ISSUE THREAD

**Issue by yimengweima0** [Zhefan-Xu/CERLAB-UAV-Autonomy#12]
你好，我安装完所有环境后，跑你第一个demo a. Autonomous Navigation: Navigating to a given goal position and avoiding collisions.，运行第三个launch文件roslaunch autonomous_flight dynamic_navigation.launch，就会立马报错
![image](https://github.com/Zhefan-Xu/CERLAB-UAV-Autonomy/assets/50518889/194b6167-b4a8-4f87-8993-734094bca5b4),跑Autonomous Navigation中的静态的导航是不报错的

**Comment by yimengweima0** [comment]
跑了Autonomous Navigation的其他的launch文件，只要与dynamic相关的均不能跑，静态的倒是可以，gazebo的运行都是正常的
![image](https://github.com/Zhefan-Xu/CERLAB-UAV-Autonomy/assets/50518889/aacacdb0-cfe9-43ea-ac31-7f059db19b23)

**Comment by yimengweima0** [comment]
@Zhefan-Xu 谢谢你，我在我的ros noteic测试确实没问题，melodic测试有问题，现在已经找到问题来源了，就是global——planner中cmakelist中opencv版本应该改为find opencv 3.2，不然可能有opencv版本冲突导致上述问题

**Comment by Dong-yin-xia** [comment]
你好，我在ros noteic测试时出现了同样的问题，

![Image](https://github.com/user-attachments/assets/0a2bfff9-89fc-4fb6-a346-cbcc2ddc29d3)，但我把global——planner中cmakelist中opencv版本应该改为找到opencv 3.2，OpenCV REQUIRED——>OpenCV 3.2 也出现同样的问题，应该怎么修改
