### ISSUE TITLE
关于mid360接入问题

### ISSUE THREAD

**Issue by Super-Iron-Man** [Zhefan-Xu/CERLAB-UAV-Autonomy#13]
您好，您这个项目很好，最近也在学习，想请问一下，如果把mid360之类的激光雷达接入navigation，配置参数需要改什么吗，除了mapping_param.yaml中的sensor_input_mode改为1之外，谢谢

**Comment by Zhefan-Xu** [comment]
@Super-Iron-Man 你好，除了你提到的mapping_param.yaml的sensor_input_mode之外，还需要增加一个point_cloud_topic，设置为LiDAR点云的topic。相应的外参在相机对应的部分修改。

我也非常有兴趣把mid360融合到这个项目中，如果你成功把激光雷达导入，欢迎发Pull Request，我们可以进一步适配

**Comment by XUTONG1024** [comment]
請問你接入成功了嗎
