### ISSUE TITLE
Can not make quadrotor takeoff

### ISSUE THREAD

**Issue by luyao2001** [Zhefan-Xu/CERLAB-UAV-Autonomy#14]
Hello! 
After I run "roslaunch uav_simulator start.launch", I can not make this quadrotor takeoff by keyboard control.
![2024-05-05 10-28-51屏幕截图](https://github.com/Zhefan-Xu/CERLAB-UAV-Autonomy/assets/61648911/acd764cb-3420-46ac-8551-bd527de32f29)

**Comment by luyao2001** [comment]
![2024-05-05 11-56-02屏幕截图](https://github.com/Zhefan-Xu/CERLAB-UAV-Autonomy/assets/61648911/b9fcf2fb-365a-4b9b-92b6-c71e1d16715e)
The "corridor_dynamic_9.world" in my computer is the above, which is very different from yours. Why ? And I can not use "rosrun autonomous_flight takeoff_and_hover_node" commend to make quadrotor takeoff.

**Comment by Zhefan-Xu** [comment]
@luyao2001 Thanks for your info. What I suggest to check:
1. When you try taking off the drone using keyboard controller, you have to click on the keyboard controller.
2. The Gazebo Plugin path might not be set correctly? This is related to putting this line  ```source path/to/uav_simulator/gazeboSetup.bash 
``` into your ```~/.bashrc```. To check whether you have set the plugin path correctly, do ```echo $GAZEBO_PLUGIN_PATH```, if everything is set correct, you should be able to see a path set under ```uav_simulator``` pkg.

You are welcome to provide more information.
