### ISSUE TITLE
How to get IMU data ?

### ISSUE THREAD

**Issue by luyao2001** [Zhefan-Xu/CERLAB-UAV-Autonomy#18]
When I use topic `/mavros/imu/data` to get IMU data, there is no output. Why ?
![2024-06-01 19-58-55屏幕截图](https://github.com/Zhefan-Xu/CERLAB-UAV-Autonomy/assets/61648911/b6b6cea1-f37f-4a96-99b9-4e78428dd1e7)

**Comment by Zhefan-Xu** [comment]
Hi @luyao2001,

I dont think there is an IMU sensor attached to the robot. If you want to get the localization data, you can directly use the odometry or pose data. Please let me know if you have further questions.

**Comment by luyao2001** [comment]
I add the following lines in the "quadrotor.urdf" file to get IMU data. I use the plugin named "libgazebo_ros_imu_sensor.so".
`  <gazebo reference="base_link">
    <gravity>true</gravity>
    <sensor name="imu_sensor" type="imu">
      <always_on>true</always_on>
      <update_rate>100</update_rate>
      <visualize>false</visualize>
      
      <pose>0 0 0 0 0 0</pose>
      <plugin filename="libllygazebo_ros_imu_sensor.so" name="imu_plugin">
        <topicName>imu_data</topicName>
        <updateRateHZ>100.0</updateRateHZ>
        <gaussianNoise>0.001</gaussianNoise>
        <xyzOffset>0 0 0</xyzOffset>
        <rpyOffset>0 0 0</rpyOffset>
        <frameName>/base_link</frameName>
        <initialOrientationAsReference>false</initialOrientationAsReference>
      </plugin>
    </sensor>
  </gazebo>`
