### ISSUE TITLE
the collision of the walker. how to check  collision?

### ISSUE THREAD

**Issue by surepay123456** [Zhefan-Xu/CERLAB-UAV-Autonomy#2]
hello，
        i am using the dynamic corridor. but i notice the collision of the walker part in only bottom. how can i check collision?

**Comment by Zhefan-Xu** [comment]
In simulation, there is a fake detector which has the bounding boxes of the dynamic obstacles. Please refer to the dynamic navigation code for getting the collision bounding boxes. Or you can modify the collision model in Gazebo files

**Comment by surepay123456** [comment]
thank u for your providing!  check collision with eyes is too hard .
