### ISSUE TITLE
Increasing the global map size

### ISSUE THREAD

**Issue by lgh5054** [Zhefan-Xu/CERLAB-UAV-Autonomy#20]
Thank you for writing good code.

Is there a way to expand the global map size to infinity in a ringbuffer-like way without storing the map?

**Comment by Zhefan-Xu** [comment]
Thanks for the question. There is probably some way to implement it but unfortunately it is currently not supported. If there is any good idea to do so, feel free to leave some suggestions or PR is welcome.
