### ISSUE TITLE
Eigen 库依赖问题导致编译失败

### ISSUE THREAD

**Issue by Study-for-20-hours-a-day** [Zhefan-Xu/CERLAB-UAV-Autonomy#22]
``在 Ubuntu 18.04 上部署项目时，遇到了编译失败的问题。使用的是 ROS Melodic 版本。

在运行 `catkin_make` 时，出现以下错误信息：

In file included from /home/user/catkin_ws/src/project_name/src/quadcopterPlugin.cpp:1:0:
/home/user/catkin_ws/src/project_name/include/project_name/quadcopterPlugin.h:9:10: fatal error: Eigen/Dense: 没有那个文件或目录
#include <Eigen/Dense>

解决方案:
问题的原因是未正确找到 Eigen 库。以下是解决步骤：
1. 确保已安装 Eigen 库：
   sudo apt-get update
   sudo apt-get install libeigen3-dev
2.修改对应包里的CMakeLists.txt 文件
添加 find_package(Eigen3 REQUIRED) 来查找 Eigen 库。
在 include_directories 部分添加 ${EIGEN3_INCLUDE_DIR} 以包含 Eigen 的头文件目录。
在 target_link_libraries 中，将 Eigen3::Eigen 链接到 quadcopterPlugin 目标。

**Comment by Zhefan-Xu** [comment]
Thanks for the solution!
