### ISSUE TITLE
gazebo 打开不显示

### ISSUE THREAD

**Issue by Yangye0526** [Zhefan-Xu/CERLAB-UAV-Autonomy#23]
[您好，我对您的工作非常感兴趣，我在进行第一个demo的测试时，遇到启动start.sh时，gazebo在这个界面卡很久，打开后没有环境没有动态人，rviz里面也没有显示，键盘控制不了起飞等操作，请问这是怎么回事？感谢回答
![ace10f3e-5147-4d9b-b6d5-05ec161fd222](https://github.com/user-attachments/assets/78bae573-1790-4004-979f-7e4315b93f31)
![c700c497-5e3f-44f4-ba55-d02f1c5d17ca](https://github.com/user-attachments/assets/1d653397-3093-401e-ab8c-1fa00fa4da2d)
![ea59af227b0226e9070e67304e8ad1a4](https://github.com/user-attachments/assets/cf9a07e3-c9e6-4f74-8bba-1433bf81d4fa)

**Comment by Zhefan-Xu** [comment]
尝试一下把这个```source path/to/uav_simulator/gazeboSetup.bash ```添加```~/.bashrc```

**Comment by Yangye0526** [comment]
![3e2e23ce-b4a5-4634-a779-2d00514c77d5](https://github.com/user-attachments/assets/05a816a2-1ce4-4b3a-b54b-5c3ecd561586)
这个在先前就已经添加进去了

**Comment by Yangye0526** [comment]
这个在先前就已经添加进去了
![3e2e23ce-b4a5-4634-a779-2d00514c77d5](https://github.com/user-attachments/assets/d60e829e-cc89-46ac-9951-21d8779772da)

**Comment by Zhefan-Xu** [comment]
这个问题大概率和plugin的路径没有设置正确相关，建议检查一下plugin的路径和实际路径

**Comment by RBBXXX** [comment]
我也遇到了同样的问题，我查看日志发现Gazebo 没有找到所需的 shader库，你可以试试在终端里source /usr/share/gazebo/setup.bash 然后再roslaunch uav_simulator start.launch，如果这样可以解决你的问题，就在~/.bashrc里面再加一行source /usr/share/gazebo/setup.bash

**Comment by RBBXXX** [comment]
> 这个在先前就已经添加进去了 ![3e2e23ce-b4a5-4634-a779-2d00514c77d5](https://github.com/user-attachments/assets/d60e829e-cc89-46ac-9951-21d8779772da)
我也遇到了同样的问题，我查看日志发现Gazebo 没有找到所需的 shader库，你可以试试在终端里source /usr/share/gazebo/setup.bash 然后再roslaunch uav_simulator start.launch，如果这样可以解决你的问题，就在~/.bashrc里面再加一行source /usr/share/gazebo/setup.bash
