### ISSUE TITLE
roslaunch autonomous_flight dynamic_navigation.launch 显示问题

### ISSUE THREAD

**Issue by Johnsonones** [Zhefan-Xu/CERLAB-UAV-Autonomy#25]
这个是我跑的结果
![1](https://github.com/user-attachments/assets/082aa0de-34ca-45ee-9ffe-ed11533417fc)
这个是你视频的结果
![2](https://github.com/user-attachments/assets/1d951136-e073-4d40-b9b4-1ae033d32523)

是不是我哪里设置的不对，还请您指教

**Comment by Zhefan-Xu** [comment]
像是建图的参数设置不正确。可以提供您的操作步骤来判断

**Comment by Johnsonones** [comment]
操作步骤与您的Readme一致，其它都一样，就这个建图不显示，而且我监听了depth信号，没有输入。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Zhefan Xu ***@***.***&gt;
发送时间: 2024年10月17日 23:30
收件人: Zhefan-Xu/CERLAB-UAV-Autonomy ***@***.***&gt;
抄送: Johnsonones ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Zhefan-Xu/CERLAB-UAV-Autonomy] roslaunch autonomous_flight dynamic_navigation.launch 显示问题 (Issue #25)





 
像是建图的参数设置不正确。可以提供您的操作步骤来判断

**Comment by Zhefan-Xu** [comment]
感觉你的autonomous_flight pkg不在simulation branch上
