### ISSUE TITLE
Error in simulation - Planner Fails 

### ISSUE THREAD

**Issue by siddharthumakarthikeyan** [Zhefan-Xu/CERLAB-UAV-Autonomy#26]
Hi,
1. I tried to launch the example. I launched the simulation with "roslaunch autonomous_flight dynamic_navigation.launch" and I when give first goal point, the quadrotor navigates in RVIZ navigates but not in gazebo and when it reaches that point, I tried to give another goal point but all I see is error and no plan is generated. I'm attaching the video of the same which can give you clear idea.

[https://drive.google.com/file/d/1x-P6u9bIwuj1XQTzKm9oJJ6tOLY6lQoQ/view?usp=sharing](url)

Please help me resolve this and when I try to give navigate to another point post first one. 

2. And also I am trying to integrate the planner with my quadrotor and all I figured is /autonomous_flight/target_state will give the desired state of the robot but I'm confused on which topics I need to give the odom and depth_points. 

3. Current simulation have any restriction to set the goal point? If so, how to expand and which file have that config.

**Comment by Zhefan-Xu** [comment]
I think the link is not valid

**Comment by siddharthumakarthikeyan** [comment]
Please check this link
https://drive.google.com/file/d/1x-P6u9bIwuj1XQTzKm9oJJ6tOLY6lQoQ/view?usp=sharing

**Comment by Zhefan-Xu** [comment]
it seems your simulation is super laggy. You have to run gazebo with a graphic card

**Comment by siddharthumakarthikeyan** [comment]
Yes. When switched my simulation to other system, it worked. Thanks!
