### ISSUE TITLE
PX4仿真环境识别障碍物有问题

### ISSUE THREAD

**Issue by YJC-666** [Zhefan-Xu/CERLAB-UAV-Autonomy#3]
为什么我用px4的模型仿真，使用移动导航，而且rviz在tf坐标系的很近周围会有彩色障碍物，但是在gazebo没有障碍物，直接给我整疑惑了

**Comment by YJC-666** [comment]
![Uploading 762b997997556a419c6bb50f0aab330.png…]()

**Comment by YJC-666** [comment]
他会生成一圈障碍物把自己围起来，让自己飞不了，我人傻了

**Comment by Zhefan-Xu** [comment]
可以发一个图看看

**Comment by YJC-666** [comment]
![Uploading 762b997997556a419c6bb50f0aab330.png…]()

**Comment by YJC-666** [comment]
![Uploading 12.png…]()

**Comment by YJC-666** [comment]
[Uploading 12.zip…]()

**Comment by YJC-666** [comment]
图片我发你邮箱
