### ISSUE TITLE
px4 simulation error

### ISSUE THREAD

**Issue by cheslee-z** [Zhefan-Xu/CERLAB-UAV-Autonomy#6]
hi, thanks for your work very much! It's really fancy. 

Now I want to run the project with px4 in simulation, and I follow the instruction in readme.md, but I meet two problem.

The first one is when I run the command `roslaunch remote_control dynamic_navigation_rviz.launch`, the RobotModel item in Rviz has an error, I try to fix it by add following line in the px4_start.launch, I don't know whether I have done it :
`<param name="robot_description" command="cat '$(find uav_simulator)/urdf/quadcopter.urdf'" />`
`<node pkg="tf" type="static_transform_publisher" name="base_link_to_map" args="0.0 0.0 0 0.0 0.0 0.0 /base_link /map 40" />`

The second one is that nothing happened after I run the command `roslaunch autonomous_flight dynamic_navigation.launch` and operate in Rviz. In another word, the navigation simulation cannot run successfully.

So could you help me? Thanks.

**Comment by Zhefan-Xu** [comment]
Hi @cheslee-z , thank you. I am assuming that you have already made non-PX4 version work. For PX4 simulation, the RobotModel will not shown. For your second question, you will have to switch the ```autonomous_flight``` into the ```px4 branch``` and do 
```
# go to your workspace
catkin_make clean 
catkin_make
```

**Comment by cheslee-z** [comment]
> Hi @cheslee-z , thank you. I am assuming that you have already made non-PX4 version work. For PX4 simulation, the RobotModel will not shown. For your second question, you will have to switch the `autonomous_flight` into the `px4 branch` and do
> 
> ```
> # go to your workspace
> catkin_make clean 
> catkin_make
> ```
> 
> Please let me know if you have further problems.

hi, thank you for your quick reply. 

Yes, I have finished non-px4 work, and then, I switch to px4 branch and re-built it following your instruction. After I run the command` roslaunch autonomous_flight dynamic_navigation.launch`, the rviz don't show the occupancy map which is shown in non-px4 work, and the waypoint doesn't work.

**Comment by cheslee-z** [comment]
I find the solution, when simulating with px4 or run in realflight, I need to add the odometry provided by vio

**Comment by onle-creator** [comment]
> I find the solution, when simulating with px4 or run in realflight, I need to add the odometry provided by vio

i also stumbled upon same problem and couldnot continue @cheslee-z can you please help me in solving it. I couldnot get more idea from what you mean by adding the odometery. It would be really helpful if you could provide more information to me to solve it

**Comment by cheslee-z** [comment]
> > I find the solution, when simulating with px4 or run in realflight, I need to add the odometry provided by vio
> 
> i also stumbled upon same problem and couldnot continue @cheslee-z can you please help me in solving it. I couldnot get more idea from what you mean by adding the odometery. It would be really helpful if you could provide more information to me to solve it

subscribe the topic about odometry such as vins by ros

**Comment by onle-creator** [comment]
> > > I find the solution, when simulating with px4 or run in realflight, I need to add the odometry provided by vio
> > 
> > 
> > i also stumbled upon same problem and couldnot continue @cheslee-z can you please help me in solving it. I couldnot get more idea from what you mean by adding the odometery. It would be really helpful if you could provide more information to me to solve it
> 
> subscribe the topic about odometry such as vins by ros

is there any way i can contact you @cheslee-z my email: kuumar.709@gmail.com

**Comment by onle-creator** [comment]
> I find the solution, when simulating with px4 or run in realflight, I need to add the odometry provided by vio

how do i add the vio in the first place and in which file do i need to change please guide

**Comment by quadrotorssfreish** [comment]
I also stumbled upon same problem，could you please tell me about which file do i need to change ?Thanks so much!
