### ISSUE TITLE
Real world experiment

### ISSUE THREAD

**Issue by cheslee-z** [Zhefan-Xu/CERLAB-UAV-Autonomy#7]
Hi, thanks for your interesting work. 

Now I am following your work, conducting real world experiments based on px4 and using vins_fusion for localization. Now I have some problems and would like to ask you about them.

To be on the safe side, I had to do offboard mode in other ways when actually flying, because using the source code would keep trying to get into offboard mode and I couldn't manually intervene when the uav went out of control, so I annotated the following part of the source code.

In `flightBase.cpp`:
```
			if (this->mavrosState_.mode != "OFFBOARD" && (ros::Time::now() - lastRequest > ros::Duration(5.0))){
	            if (this->setModeClient_.call(offboardMode) && offboardMode.response.mode_sent){
	                cout << "[AutoFlight]: Offboard mode enabled." << endl;
	            }
	            lastRequest = ros::Time::now();
	        } else {
	            if (!this->mavrosState_.armed && (ros::Time::now() - lastRequest > ros::Duration(5.0))){
	                if (this->armClient_.call(armCmd) && armCmd.response.success){
	                    cout << "[AutoFlight]: Vehicle armed." << endl;
	                }
	                lastRequest = ros::Time::now();
	            }
	        }
```

And In `dynamicNavigation.cpp`:
`this->takeoff();`

However, after the uav took off, I switched to offboard mode and designated the waypoint of the drone through rviz, but it seems that the program did not start the planning work, as the terminal did not output` [AutoFlight]: Replan for new goal position`. The whole program seems to be stuck in an endless loop of the following program:
```
		while (ros::ok() and not this->isReach(ps)){
			currTime = ros::Time::now();
			double t = (currTime - startTime).toSec();

			if (t >= endTime){ 
				psT = ps;
			}
			else{
				double currYawTgt = yawCurr + (double) direction * t/endTime * yawDiffAbs;
				geometry_msgs::Quaternion quatT = AutoFlight::quaternion_from_rpy(0, 0, currYawTgt);
				psT.pose.orientation = quatT;
				
			}
			// this->updateTarget(psT);
			target.position.x = psT.pose.position.x;
			target.position.y = psT.pose.position.y;
			target.position.z = psT.pose.position.z;
			target.yaw = AutoFlight::rpy_from_quaternion(psT.pose.orientation);
			this->updateTargetWithState(target);
			// cout << "here" << endl;
			ros::spinOnce();
			r.sleep();
		}
```

I have completed the simulation experiment based on px4, and I have changed the parameters in the configuration file for my real depth camera, compared to the simulation experiment, where do you think I might have gone wrong？

Another minor issue was when I started rviz, it sometimes seemed impossible to visualize the created dynamic map, but the `/dynamic_map/inflated_voxel_map `topic kept getting messages.

Thank you for your precious time!

**Comment by Zhefan-Xu** [comment]
@cheslee-z Hi, thanks for your feedback. Here is my thoughts:
1. Regarding your safety consideration, your modification seems fine to me. 
2. For endless loop, I am also aware of that issue but happens very occasionally. I would very appreciate if you can go deeper  to check what causes this endless loop and feel free to provide your feedback. I am planning to commit a revised version for solving that issue and also feel free to create a pull request if you have figured it out.
3. For the dynamic map visualization, if you can get message but cannot visualize it, I would suggest you check your network  (is it because you the laptop didn't receive msg from the drone?). Or is the visualizatoin frame set to the correct one (i.e. "map"). Feel free to provide more information.

**Comment by cheslee-z** [comment]
@Zhefan-Xu Hi, thanks for your quick reply.

Now I update the follow-up:

The dead loop is because I did not take off during the test, so the orientation of the drone has not reached the expected value. When I manually correct the orientation of the drone, the program will jump out of the loop and really start the planning task.
But what's interesting is that this ros node automatically shuts down right away, apparently because of a problem with the eigen library. I checked about the log, this error `ERROR: Ran out of pool, index= 27 76 -1` occasionally appears in simulation, but does not cause the program to die.
![2024-03-13_22-02](https://github.com/Zhefan-Xu/CERLAB-UAV-Autonomy/assets/46998045/480102c6-2762-4937-a6eb-cff2c4a0391d)

after I comment out `this->moveToOrientation(yaw, this->desiredAngularVel_);`, I conducted a new round of real flight experiments, and only a few times the program did not automatically interrupt. In the few successful planning experiments, the drone did not accurately track the trajectory, but instead demonstrated a higher speed than the set desired speed, which was set as a parameter of `desired_velocity: 1.5 # m/s`. The PID parameters of the tracking controller have been verified by other planners, so the problem of tracking the controller is ruled out.

**Comment by Zhefan-Xu** [comment]
@cheslee-z 

Can I ask what is the your testing height (z)? There is a parameter for height constraint in the planner parameter. 

Also, are you using the local coodinate? From the msg output, it said path search want to find path between (0.13, -0.02. -3.90) to (3.13, -3.2, 0.05). I am a little bit confused with this data.  If you start the drone at the ground, why there exist -3.90m in z direction?

**Comment by cheslee-z** [comment]
> @cheslee-z
> 
> Can I ask what is the your testing height (z)? There is a parameter for height constraint in the planner parameter.
> 
> Also, are you using the local coodinate? From the msg output, it said path search want to find path between (0.13, -0.02. -3.90) to (3.13, -3.2, 0.05). I am a little bit confused with this data. If you start the drone at the ground, why there exist -3.90m in z direction? (Z should never go below zero)

@Zhefan-Xu 

I think when specifying waypoint in rviz, the default height is 1m, which is also set by default in the code, and I have not changed it.

For the parameters of height constraint, you mean `bspline_traj/min_height` and `bspline_traj/max_height`? When I adjust these two parameters to 0.0 and 3.0 respectively, the node still terminates automatically, as shown in the figure below.

![2024-03-15_11-43](https://github.com/Zhefan-Xu/CERLAB-UAV-Autonomy/assets/46998045/09e03427-55ff-4a64-b6bb-95e0da245c7c)


Also, I didn't pay much attention to the problem of coordinate system, but for the parameter of `odom_topic`, I set to `odom_topic: /mavros/local_position/odom`. I found that this parameter may still drift when the data of  localization topic `/vins_fusion/imu_propagate` from vio does not drift. I think what you said about the z direction being less than zero is probably caused by that, because I've been putting the UAV on my desktop and not moving. So I set odom_topic to` /vins_fusion/imu_propagate` again. The following is the result of my experiment.

![2024-03-15_11-59](https://github.com/Zhefan-Xu/CERLAB-UAV-Autonomy/assets/46998045/f9cbb740-e87d-493b-9746-585f41baece2)


Maybe the key of the problem is not the coordinate system, I still need to further study the code. If you have any suggestions, could you please let me know at your convenience? Thank you very much!

**Comment by Zhefan-Xu** [comment]
@cheslee-z 
according to what you described: "Also, I didn't pay much attention to the problem of coordinate system, but for the parameter of odom_topic, I set to odom_topic: /mavros/local_position/odom. I found that this parameter may still drift when the data of localization topic /vins_fusion/imu_propagate from vio does not drift."

It seems like your VIO system is not working properlly (since you said there exits drift which can make the height estimation go to -3).  I would suggest you to figure out the correct px4 VIO setup before running any flight test. 

Also, as far as I remember, px4 mavros has different coordinate system from vins. In px4, x is the forward direction and y is the forward direction in vins framework. 

Please let me know if you have any further questions.

**Comment by Zhefan-Xu** [comment]
I am closing the issue. Feel free to reopen if you have any further updates.

**Comment by cheslee-z** [comment]
> @cheslee-z according to what you described: "Also, I didn't pay much attention to the problem of coordinate system, but for the parameter of odom_topic, I set to odom_topic: /mavros/local_position/odom. I found that this parameter may still drift when the data of localization topic /vins_fusion/imu_propagate from vio does not drift."
> 
> It seems like your VIO system is not working properlly (since you said there exits drift which can make the height estimation go to -3). I would suggest you to figure out the correct px4 VIO setup before running any flight test.
> 
> Also, as far as I remember, px4 mavros has different coordinate system from vins. In px4, x is the forward direction and y is the forward direction in vins framework.
> 
> Please let me know if you have any further questions.

I checked my vio Settings and there was no problem. I finally found that the positioning height drift was caused by the fact that the altitude source setting of the px4 was set to the barometer main.

I'm still trying to replicate your work. I've also found that localization with vio is prone to drift, but optitrack is much better.

Thank you.
