### ISSUE TITLE
libonboard_detector.so: undefined reference to `cv::Mat::Mat()'

### ISSUE THREAD

**Issue by ranjithlesoko** [Zhefan-Xu/CERLAB-UAV-Autonomy#8]
/usr/bin/ld: /home/new_drone_ws/devel/lib/libonboard_detector.so: undefined reference to `cv::Mat::Mat()'
collect2: error: ld returned 1 exit status

**Comment by Zhefan-Xu** [comment]
@ranjithlesoko Sorry I am not sure what's your question.

**Comment by ranjithlesoko** [comment]
@Zhefan-Xu  when i  try to make catkin_make command i getting this error

**Comment by Zhefan-Xu** [comment]
@ranjithlesoko Hi, this looks like an opencv error. Please try to correctly install and configure opencv first and then make this repo.

**Comment by ranjithlesoko** [comment]
i installed opencv 4.6.0  with cuda this work or not ? ,and which version is suitable and I'm using jetson xeiver nx
