### ISSUE TITLE
Question about building VINS-Fusion with GPU support using OpenCV 4.6.0

### ISSUE THREAD

**Issue by ranjithlesoko** [Zhefan-Xu/CERLAB-UAV-Autonomy#9]
I'm trying to build VINS-Fusion with GPU support using OpenCV 4.6.0, but I'm encountering some difficulties. Specifically, I'm unsure about the correct configuration and build steps required to enable GPU acceleration with OpenCV 4.6.0.

I've already followed the installation instructions for VINS-Fusion and have successfully built it without GPU support. However, I'm not sure how to incorporate OpenCV 4.6.0 with CUDA support into the build process to enable GPU acceleration.

Could someone provide guidance or pointers on how to correctly configure and build VINS-Fusion with GPU support using OpenCV 4.6.0?

Environment:
- Operating System:  Ubuntu 20.04
- OpenCV Version: 4.6.0
- CUDA Toolkit Version:  11.4
- Model: jetson xevier nx

**Comment by Zhefan-Xu** [comment]
Hi @ranjithlesoko , you probably want to post your issue in this repo: https://github.com/HKUST-Aerial-Robotics/VINS-Fusion. This repo does not include VIO.
